# Generated by Django 3.1.7 on 2021-06-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalabel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalabel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
